### ISSUE TITLE
V1 - Current development track

### ISSUE THREAD

**Issue by curryrasul** [zkemail/email-wallet#1]
## Circuits
* [x] PSI circuit
* [x] Circom tests for all circuits
* [x] Script to generate inputs and vkeys for circuits
* [x] Script to generate proof for circuits
* [x] _Circuit for relayer transport?_

## Contracts
* [x] Unregistered funds, claim functionality and refund mechanism
* [x] Proof verifier for all circuits
* [ ] Extension flow with separate account per user
* [x] Use Token Registry and DKIM Registry from zk-email-verify
* [ ] Relayer transport mechanism
* [x] Extension management functionality (install/remove ext for users)
* [x] Fee management and relayer incentives
* [ ] PSI point registration
* [x] Extension registry on chain? (name->address mapping for extensions)
* [x] Unclaimed state for extensions
* [ ] _Relayer registry on chain with hostnames?_
* [x] Unit test for all functionality to cover all cases
* [x] Integration test with actual verifiers
* [x] Deploy scripts

## ## Relayer
 * [x] Handle account initialisation flow (user reply to invitation email) + proof generation
 * [x] Handle claim unclaimed funds for newly initialised account
 * [x] Handle claim unclaimed funds for existing account when randomness received (from other relayer or via public api)
 * [ ] Contact other relayer to see if the recipient exist (PSI)
   * [ ] Send invitation email if not
   * [ ] Communicate with other relayer to generate recipient proof
 * [ ] Handle PSI requests and proof generation from other relayer
 * [x] Proof generation for normal wallet operations (send, set ext, extensions commands...)
 * [x] Handle account transport emails (become the new relayer using user's original init email)
 * [x] Register unclaimed funds for user if no-relayer acknowledge existence of recipient
 * [x] DB: Store all unclaimed fund email randomness and check them when new account is initialised
 * [x] Handle automatic send if the sender deposit tokens later?
 * [x] API:
   * [ ] API for the UI to read wallet details of a user
   * [ ] Authentication via magic link
   * [ ] API to return ETH, TOKEN balance of a user
   * [ ] API to list users transaction history
   * [ ] API to list all extensions installed by a user
   * [ ] _Generic API to return extension state of a user?_

## UI
 * [x] UI to login using email + magic link
 * [x] Show ETH and token balances
 * [x] Email generation for wallet operations
 * [x] Extension store page - install and remove extensions
 * [ ] Setting section to choose the user's relayer
 * [x] UI to deposit funds to an email wallet from EOA
 * [x] Embed UI created by extension dev?

## Docs:
 * [ ] "How to use" page
 * [ ] "How to implement extension" page

**Comment by AtHeartEngineer** [comment]
@curryrasul Hey! Would you mind updating this to show what still needs work done?

**Comment by saleel** [comment]
I think we can close this issue. Most of the tasks here are done already, and few are no longer relevant based on our current UX.
We can create separate individual issues for things that are still needed.

**Comment by Divide-By-0** [comment]
Agreed. 

> I think we can close this issue. Most of the tasks here are done already, and few are no longer relevant based on our current UX. We can create separate individual issues for things that are still needed.
