### ISSUE TITLE
Clarification on bytes unpacking logic

### ISSUE THREAD

**Issue by bweick** [zkemail/email-wallet#10]
Brian from zkp2p here! Just wanted to make sure I was understanding some logic in the `StringUtils` function.

1. Am I right to assume that `maxBytes` needs to be a multiple of `packSize` here?
https://github.com/zkemail/email-wallet/blob/461782c9f3a9cf9ef21fbd8628414692e45223a0/packages/contracts/src/utils/StringUtils.sol#L74

2. Similarly it seems that `packSize` is fixed here to `7` is that right? Since that's how circom does it's packing.
`https://github.com/zkemail/email-wallet/blob/461782c9f3a9cf9ef21fbd8628414692e45223a0/packages/contracts/src/utils/StringUtils.sol#L82`

3. If I can suggest a different function signature could it look something like this:
`function convertPackedBytesToBytes(uint256[] memory packedBytes, uint256 signals) internal pure returns (string memory extractedString)`

We can then treat the `packSize` as a `constant` --> `PACK_SIZE` and calculate `maxBytes` as follows:
`uint256 maxBytes = signals * PACK_SIZE`

Not sure `signals` is the best name but this seems a bit cleaner. You also may be designing for different potential pack sizes. Lemme know what you think.

**Comment by Divide-By-0** [comment]
Yes, it's fixed to 7 arbitrarily, even though we changed the packed size in circom. Correct that the 7 should be a constant set in the file, and maxBytes dependent on that value.

**Comment by Divide-By-0** [comment]
Here's the fix PR:
https://github.com/zkemail/zk-email-verify/pull/125

I've fixed the your point 2 bug, and added functions to more or less address your 1 and 3 points.
