### ISSUE TITLE
Token amount gets truncated in `_computeMaskedSubjectForEmailOp`

### ISSUE THREAD

**Issue by Philogy** [zkemail/email-wallet#4]
In [EmailWalletCore.sol#L756](https://github.com/zkemail/email-wallet/blob/feat/v1/packages/contracts/src/EmailWalletCore.sol#L756) the `walletParams.amount` gets divided by $10^d$ before being converted to string. In Solidity the `/` operator is integer division, meaning any fractional value will get round down, acting as the floor operator.

This means that `Strings.toString(walletParams.amount / (10 ** token.decimals())),` for an amount of e.g. `21.378` would result in `"21"`, this could be bad?

**Comment by saleel** [comment]
Thank you for pointing out. This is a known issue and yet to be implemented. I was actually working on the same thing.
Contracts are still in progress - and there some small functionalities and optimisation to do.

**Comment by saleel** [comment]
This is fixed now
