### ISSUE TITLE
Move IMAP listener from Relayer

### ISSUE THREAD

**Issue by saleel** [zkemail/email-wallet#41]
This is an idea to improve relayer infra:

- Add HTTP API in relayer to receive new email
- Response is the email that should be sent to the user
- IMAP listener can be a separate service that calls the Relayer server when there is a new email, and send the HTTP response (email) back to the user.

Advantages:
- AWS SES can be used to listen to emails and call the relayer - we can avoid connection issues with IMAP
- The relayer can run in a serverless fashion - can also explore running the full relayer in modal.com
- For local use, IMAP listener service can be run separately - Docker compose can be setup for running everything.

**Comment by Bisht13** [comment]
Completed
