### ISSUE TITLE
Simplify Account Key matching in registration emails

### ISSUE THREAD

**Issue by saleel** [zkemail/email-wallet#43]
Currently account key is checked by looking for `CODE:{accountKeyHex}` in email headers.

Change this to use `accountkey_{accountKeyHex}`

The idea is to remove colon, so this can also be part of to address.

**Comment by saleel** [comment]
@Divide-By-0 Please review if the new format will work.

**Comment by Divide-By-0** [comment]
@saleel your thoughts on making it either colon or underscore? If it is in the subject, I want it to be legible

**Comment by saleel** [comment]
https://www.notion.so/proofofemail/Email-Wallet-Protocol-Updates-after-1-14-7b5999d2fb874dad9406402c899cb5bf?pvs=4#7c196a458a184b5ca4e50832f2df2755

Had a discussion with @SoraSuegami and is thinking of `ACCOUNTKEY.0x(hex(accountKey))`. What do you think?
