### ISSUE TITLE
Script to update Token registry

### ISSUE THREAD

**Issue by saleel** [zkemail/email-wallet#7]
Create a script to update tokens not in TokenRegistry contract based on the default uniswap list - https://github.com/Uniswap/default-token-list/tree/main/src/tokens

**Comment by Divide-By-0** [comment]
I assume you mean token registry here not dkim registry

**Comment by Divide-By-0** [comment]
This doesn't belong in email-wallet, its a more general SDK tool. I have pushed some code here:
https://github.com/zkemail/zk-email-verify/commit/c62bf348138d0d2db89e45a7f599a53ce560b806

You need to add the poseidon hash yourself on the end of the function for the new mailserver key format.

**Comment by saleel** [comment]
> This doesn't belong in email-wallet, its a more general SDK tool. 

This issue is for TokenRegistry, not DKIM. TokenRegistry is only applicable for email wallet or other wallet projects, not for zk-email in general 🤔

**Comment by Divide-By-0** [comment]
I'm an idiot I was looking at the old title lol. My brain is clearly off, I'm going to bed lol.
